[NFC] Insert truncation/primal just before statement
JuliaDiff/Diffractor.jl pull request #181
Opened 2023-07-11 09:20 UTC by oxinabox

This is a more elegant way to handle this than https://github.com/JuliaDiff/Diffractor.jl/pull/162
we just insert the function that is applied to the arguments just before the statement, rather than just after the argument.
thus avoiding need to dodge phi nodes, and making the ir code more readable.
This is also consistent with how we handle `GlobalRef`s

2023-07-11 13:39 UTC, Keno requested changes
I don't think this is necessarily correct. It's certainly not NFC

2023-07-11 15:57 UTC, oxinabox commented
Isn't it?
By no functional change I mean, it should have no user visible effects.
But it's not a simply code cleanup that is true. It does change the IR generated.
But not in a way that should effect what actually ends up running.
But if I broke it then obviously it would.

What does it get incorrect?

for some input
```
%1 = a
%2 = b
%3 = c
%4 = f(%1)
```
Before this PR we would get
```
%1 = a
%2 = primal(%1)
%3 = b
%4 = c
%5 = f(%2)
```
After this PR we would get 
```
%1 = a
%2 = b
%3 = c
%4 = primal(%1)
%4 = f(%4)
```

2023-07-11 21:15 UTC, Keno commented
What happens if the `ssa` is a PhiNode? What prevents us from trying to insert a call in the middle of the phi block?

2023-07-12 04:49 UTC, oxinabox commented
ooh, I never considered that. I was only thinking of `invoke`s and `call`s.
Yeah, this approach won't work out.

2023-07-12 04:49 UTC, closed without merging